### ISSUE TITLE
[feature] add url wildcard support

### ISSUE THREAD

**Issue by madcpt** [ZhiaDev/mac-proxy-manager#1]
thanks for creating such an elegant menu app!

I find this feature quite useful in my case, could you consider supporting this in the future?

**Comment by ZhiaDev** [comment]
Hello @madcpt, and thank you for your kind words about the app!🌟 I appreciate your suggestion regarding the addition of URL wildcard support. If by any chance you are referring to the "bypass list" feature, I'm pleased to inform you that I've already planned to implement it in the next two or three weeks.

I apologize for the delayed response to your message from a few months ago. Your feedback is valuable, and I appreciate your patience. If you have any more suggestions or questions, feel free to share them. I'm committed to improving the app and providing a better user experience. Thank you for your understanding!

**Comment by ZhiaDev** [comment]
Hello @madcpt,

I have added the bypass proxy list feature to the Proxy Manager app in the settings. You can download the new version from the [releases](https://github.com/ZhiaDev/mac-proxy-manager/releases).
