### ISSUE TITLE
Add Bypass list support

### ISSUE THREAD

**Issue by sayanroy7** [ZhiaDev/mac-proxy-manager#2]
First of all, I'd like to thank you for creating a great menu app, and I found it extremely useful. I would like to check the possibility if we can include the "bypass list" feature for the proxy? this is a standard settings in almost all the proxy configurations, and would be a much needed addition to this app.

**Comment by ZhiaDev** [comment]
Hello @sayanroy7, and thank you for your kind words! 🌟 I appreciate your suggestion about the "bypass list" feature for proxies, and I agree it could be a valuable addition. I'm pleased to inform you that I've already planned to include this feature in the upcoming updates. You can expect it to be part of the program in the next two or three weeks. I appreciate your patience and understanding. If you have any more feedback or suggestions, feel free to share them. Thanks again for your support! 🚀

**Comment by ZhiaDev** [comment]
Hello @sayanroy7,

I have added the bypass proxy list feature to the Proxy Manager app in the settings. You can download the new version from the [releases](https://github.com/ZhiaDev/mac-proxy-manager/releases).
